const legalStyles = `
.legal-page h2 {
  font-family: 'Roboto Condensed', sans-serif;
  color: #FFFFFF;
  font-size: clamp(20px, 3vw, 24px);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: -0.5px;
  margin: 40px 0 16px;
}
.legal-page h2:first-of-type { margin-top: 0; }
.legal-page p,
.legal-page li {
  font-family: 'Inter', sans-serif;
  color: #FFFFFF;
  font-size: 15px;
  line-height: 1.7;
}
.legal-page p { margin: 0 0 14px; }
.legal-page ul {
  margin: 0 0 16px;
  padding-left: 20px;
}
.legal-page li { margin-bottom: 8px; }
.legal-page a {
  color: #E88A1A;
  text-decoration: none;
  border-bottom: 1px solid rgba(232,138,26,0.4);
}
.legal-page a:hover {
  border-bottom-color: #E88A1A;
}
.legal-page strong {
  color: #FFFFFF;
  font-weight: 600;
}
.legal-intro {
  border-left: 3px solid #E88A1A;
  padding: 0 0 0 20px;
  margin: 0 0 40px;
  font-style: italic;
  color: #E88A1A !important;
  font-family: 'Roboto Condensed', sans-serif;
  font-size: 16px !important;
  letter-spacing: 0.02em;
}
`;

const EFFECTIVE_DATE = 'April 14, 2026';
const CONTACT_EMAIL = 'seekers@warofthesphinx.com';

export function Terms() {
  return (
    <>
      <style>{legalStyles}</style>
      <div
        style={{
          minHeight: '100vh',
          paddingTop: 24,
        }}
      >
        <div
          className="legal-page"
          style={{
            maxWidth: 780,
            margin: '0 auto',
            padding: '0 16px 80px',
          }}
        >
          <div style={{ marginBottom: 40 }}>
            <p
              style={{
                fontFamily: "'Roboto Condensed', sans-serif",
                color: '#E88A1A',
                fontSize: 12,
                letterSpacing: 2,
                textTransform: 'uppercase',
                margin: '0 0 12px',
              }}
            >
              Terms of Service
            </p>
            <h1
              style={{
                fontFamily: "'Roboto Condensed', sans-serif",
                color: '#FFFFFF',
                fontSize: 'clamp(32px, 6vw, 48px)',
                fontWeight: 900,
                textTransform: 'uppercase',
                letterSpacing: -0.5,
                lineHeight: 1.05,
                margin: 0,
              }}
            >
              The Terms of Passage
            </h1>
            <p
              style={{
                fontFamily: "'Inter', sans-serif",
                color: '#AAAAAA',
                fontSize: 13,
                margin: '16px 0 0',
              }}
            >
              Effective {EFFECTIVE_DATE}
            </p>
          </div>

          <p className="legal-intro">
            Every threshold has its rules. Cross it, and you agree to them. Read what follows
            carefully — it governs your use of this archive.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            These Terms of Service ("Terms") form a binding agreement between you and the team
            behind <strong>War of the Sphinx</strong> ("we", "us", or "the Archive"). By accessing
            or using the Platform — whether by browsing, speaking with The Griot, subscribing to
            updates, or any other means — you agree to these Terms. If you do not agree, do not
            use the Platform.
          </p>

          <h2>2. Who Can Use the Platform</h2>
          <p>
            You must be at least 13 years old to use the Platform. If you are between 13 and the
            age of majority in your jurisdiction, you may only use the Platform with the consent
            of a parent or legal guardian. The Platform is not intended for, and we do not
            knowingly permit, users under 13.
          </p>

          <h2>3. The Platform</h2>
          <p>
            The Platform is provided as a promotional and informational resource for the War of the
            Sphinx comic book series. Its features include, without limitation: informational
            pages about the series, an AI-driven chat experience ("The Griot"), voice playback of
            Griot responses, an art gallery, and email subscription. We may add, modify, or remove
            features at any time without prior notice.
          </p>

          <h2>4. The Griot (AI Disclaimer)</h2>
          <p>
            <strong>The Griot is an AI-driven fictional character.</strong> Its responses are
            generated by third-party language models and are intended solely for entertainment in
            the context of the War of the Sphinx narrative.
          </p>
          <ul>
            <li>Responses are fictional. They do not represent facts about the real world.</li>
            <li>The Griot does not provide medical, legal, financial, psychological, or any other form of professional advice.</li>
            <li>AI systems can and do produce inaccurate, offensive, or unintended output. We make no warranty that Griot responses will be accurate, appropriate, or free of error.</li>
            <li>Do not submit personal, sensitive, confidential, or otherwise protected information to The Griot. Messages are transmitted to third-party AI providers and stored in our database.</li>
          </ul>

          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Platform for any unlawful purpose or in violation of any applicable law or regulation.</li>
            <li>Attempt to probe, scan, overwhelm, or reverse-engineer the Platform or its APIs.</li>
            <li>Circumvent or attempt to circumvent rate limits, authentication, or other access controls.</li>
            <li>Automate interactions with The Griot in a way that generates substantial API usage at our expense (scraping, bulk querying, denial-of-service).</li>
            <li>Impersonate any person, misrepresent your affiliation with any person or entity, or submit false information.</li>
            <li>Submit content to The Griot that is harassing, threatening, hateful, sexually explicit, or that depicts or promotes violence.</li>
            <li>Upload, transmit, or attempt to transmit malware, viruses, or other malicious code.</li>
            <li>Extract, scrape, reproduce, or redistribute the Platform's content or code without our prior written consent.</li>
          </ul>
          <p>
            We reserve the right to rate-limit, block, suspend, or terminate access for any user
            we believe is violating these Terms, without notice.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            The <strong>War of the Sphinx</strong> name, logo, setting ("Neo-Nubia"), characters,
            artwork, story, and associated creative elements are the original intellectual property
            of their respective creators and are protected by copyright, trademark, and other
            applicable laws.
          </p>
          <p>
            No part of the Platform — including artwork displayed in the Gallery, Griot conversations,
            lore pages, or any related content — may be reproduced, modified, distributed, publicly
            displayed, or used to train machine learning models without our prior written consent.
            Fan discussion, non-commercial reference, and sharing via the Platform's own share
            functionality (where present) are permitted within reasonable fair-use limits.
          </p>

          <h2>7. User-Submitted Content</h2>
          <p>
            Content you submit to the Platform — including email addresses, chat messages, and any
            other information — remains your property. By submitting it you grant us a worldwide,
            non-exclusive, royalty-free license to store, process, and use it to operate and improve
            the Platform, and to send you communications you have opted into.
          </p>
          <p>
            You represent and warrant that any content you submit (a) is yours to submit and (b)
            does not violate the rights of any third party or any applicable law.
          </p>

          <h2>8. Email Subscriptions</h2>
          <p>
            Submitting your email subscribes you to updates about War of the Sphinx. You may
            unsubscribe at any time via the link in any of our emails or by emailing{' '}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>. We do not share your email
            with third parties for their own marketing purposes.
          </p>

          <h2>9. Third-Party Services and Links</h2>
          <p>
            The Platform integrates services from third parties (Firebase, Cloudinary, Anthropic,
            ElevenLabs, Resend, and others) and may link to external sites. We do not control and
            are not responsible for the content, policies, or practices of any third-party service
            or site. Your use of those services is governed by their own terms and privacy policies.
          </p>

          <h2>10. Disclaimers</h2>
          <p>
            THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND,
            WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE
            PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS,
            OR THAT ANY DEFECTS WILL BE CORRECTED.
          </p>

          <h2>11. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE, OUR AFFILIATES, OR OUR
            LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
            DAMAGES, OR ANY LOSS OF PROFITS, REVENUES, DATA, OR GOODWILL, ARISING OUT OF OR IN
            CONNECTION WITH YOUR USE OF THE PLATFORM, REGARDLESS OF THE LEGAL THEORY AND EVEN IF
            WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL AGGREGATE LIABILITY
            FOR ANY CLAIMS ARISING FROM OR RELATED TO THE PLATFORM WILL NOT EXCEED ONE HUNDRED
            US DOLLARS (USD $100).
          </p>
          <p>
            Some jurisdictions do not allow the exclusion or limitation of certain damages; in
            those jurisdictions, the above limitations apply only to the maximum extent permitted
            by law.
          </p>

          <h2>12. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless War of the Sphinx and its creators,
            contributors, and agents from and against any claims, liabilities, damages, losses,
            and expenses (including reasonable legal fees) arising out of or in any way connected
            with your violation of these Terms or your misuse of the Platform.
          </p>

          <h2>13. Termination</h2>
          <p>
            We may suspend or terminate your access to the Platform at any time, for any reason or
            no reason, with or without notice. Provisions of these Terms that by their nature should
            survive termination — including intellectual property, disclaimers, limitation of
            liability, and governing law — will survive.
          </p>

          <h2>14. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the United States, without regard to its
            conflict-of-laws principles. Any disputes arising out of or related to these Terms or
            the Platform shall be resolved in the state or federal courts located in the United
            States, and you consent to the personal jurisdiction of those courts.
          </p>

          <h2>15. Changes to These Terms</h2>
          <p>
            We may revise these Terms from time to time. The "Effective" date at the top of this
            page reflects the latest version. Continued use of the Platform after a change
            constitutes acceptance of the revised Terms. Material changes will be announced on the
            site or by email to subscribers.
          </p>

          <h2>16. Contact</h2>
          <p>
            Questions about these Terms?{' '}
            <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
          </p>
        </div>
      </div>
    </>
  );
}
